### ISSUE TITLE
Open/Edit doesn't work for files without extension

### ISSUE THREAD

**Issue by Toastbroti** [matthiaaas/ftp#36]
You can't open files without filename extensions.

**Comment by matthiaaas** [comment]
on which platform (macOS/Windows/Linux)?

**Comment by Toastbroti** [comment]
Windows

**Comment by matthiaaas** [comment]
Yep, this is because Windows doesn't know how to open the file (probably there pops up a native error message).
This will be fixed if there's the option to always open files in a specific app. Unfortunately Windows makes this function pretty hard to implement and auto-updating the remote file is not available for Windows either.
